services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "5001:5001"
    volumes:
      - ipfs_data:/data/ipfs
    restart: unless-stopped

  gateway:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - path: ./.env
        required: true
    depends_on:
      - ipfs
    restart: unless-stopped

volumes:
  ipfs_data:
  postgres_data:
