services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

  ipfs:
    image: ipfs/kubo:latest
    volumes:
      - ipfs_data:/data/ipfs
    restart: unless-stopped
    networks:
      - backend

  megarouter:
    build: .
    ports:
      - "3000:3000"
      - "9090:9090"
    env_file:
      - .env
    environment:
      - METRICS_PORT=9090
      - LOKI_URL=https://loki.infra.megayours.com
    depends_on:
      - postgres
      - ipfs
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # HTTP Router
      - "traefik.http.routers.megarouter.rule=Host(`router1.testnet.megayours.com`)"
      - "traefik.http.routers.megarouter.entrypoints=web"
      # HTTPS Router
      - "traefik.http.routers.megarouter-secure.rule=Host(`router1.testnet.megayours.com`)"
      - "traefik.http.routers.megarouter-secure.entrypoints=websecure"
      - "traefik.http.routers.megarouter-secure.tls=true"
      - "traefik.http.routers.megarouter-secure.tls.certresolver=letencrypt"
      # Service (shared between both routers)
      - "traefik.http.services.megarouter.loadbalancer.server.port=3000"
    networks:
      - backend
      - traefik

volumes:
  ipfs_data:
  postgres_data:

networks:
  backend:
    name: backend
  traefik:
    external: true